MODEL:
  NAME: 'mobilenet'
  CLASSES: ('hwear', 'hunwear')
  NUM_CLASSES: 3
EPOCH: 500
NUM_DECONV_LAYERS: 3
DECONV_WITH_BIAS: False
MULTI_GPU: True
SOLVER:
  NAME: 'sgd'
  WARMUP: True
  WARMUP_EPOCH: 50
  LR: 0.0002
  SCHEDULER:
    EPOCHS: (300, 400)
DATA:
  SIZE: (128, 256)
TRAIN_DIR: ('data/upper_cropped_1', 'data/upper_cropped_2', 'data/upper_cropped_3')
VAL_DIR: ('data/upper_cropped_3',)
BATCH_SIZE: 48
OUTPUT_DIR: 'test'
